import Head from 'next/head'
import Image from 'next/image'
import Carousel from '../components/Carousel'
import Dropdown from '../components/Dropdown'

export default function Home({data}) {

  const uniqueArr = [... new Set(data.map(datum => datum.product_name))]
  const states = [... new Set(data.map(datum => datum.address.state))]
  const city = [... new Set(data.map(datum => datum.address.city))]
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='min-h-screen bg-[#292929] grid grid-cols-12'>
        <section className='col-span-12 md:col-span-2 md:py-12'>
          <div className='bg-black px-4 md:py-6 flex justify-around md:block w-[90%] mx-auto rounded-[15px]'>
            <h2 className='text-[#A5A5A5] text-xl md:border-white md:border-b-2 md:pb-4'>Filters</h2>
            <Dropdown state={uniqueArr} name={'product'}/>
            <Dropdown state={states} name='States'/>
            <Dropdown state={city} name='city'/>
          </div>
        </section>
        <section className='col-span-12 md:col-span-10 py-12'>
          <h2 className='w-[90%] mx-auto text-3xl font-bold text-white opacity=[87]'>Edvora</h2>
          <p className='w-[90%] mx-auto pt-10 text-xl text-white opacity-50'>Product Name</p>
          {uniqueArr.map((item, i)=>{
            const result = data.filter(datum => datum.product_name === item )
            return (
              <div className={i !== 0 ? 'py-12' : 'py-0'}>
             <p className='text-white pb-4 mb-6 border-b-2 border-zinc-300 mx-auto w-[90%]'>{item}</p>
            <Carousel result={result} index={i}/>
            </div>
            )
          })
         }
        </section>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
 const res = await fetch('https://assessment-edvora.herokuapp.com');
 const data = await res.json()
  return {
    props: {
      data
    }, 
  }
}